export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";

export const GET_DISEASE_LIST_SUCCESS = "GET_DISEASE_LIST_SUCCESS";
export const GET_DISEASE_LIST_FAILURE = "GET_DISEASE_LIST_FAILURE";

export const GET_DISEASE_LIST = "GET_DISEASE_LIST";
