export const SET_LOADING_TRUE = "SET_AUTHENTICATION_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_AUTHENTICATION_LOADING_FALSE";

export const FETCH_USER_LIST_SUCCESS = "FETCH_USER_LIST_SUCCESS";
export const FETCH_USER_LIST_FAILURE = "FETCH_USER_LIST_FAILURE";

export const FETCH_ADMIN_LIST_SUCCESS = "FETCH_ADMIN_LIST_SUCCESS";
export const FETCH_ADMIN_LIST_FAILURE = "FETCH_ADMIN_LIST_FAILURE";
