export const SET_READY_TRUE = "SET_READY_TRUE";
export const SET_READY_FALSE = "SET_READY_FALSE";
export const SET_USER = "SET_USER";

export const LOGOUT = "LOGOUT";
export const SET_LOGOUT_LOADING_TRUE = "SET_LOGOUT_LOADING_TRUE";
export const SET_LOGOUT_LOADING_FALSE = "SET_LOGOUT_LOADING_FALSE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED_WITH_ERROR = "LOGIN_FAILED_WITH_ERROR";
export const SET_LOGIN_LOADING_TRUE = "SET_LOGIN_LOADING_TRUE";
export const SET_LOGIN_LOADING_FALSE = "SET_LOGIN_LOADING_FALSE";
