export const SET_CART_LOADING_TRUE = "SET_CART_LOADING_TRUE";
export const SET_CART_LOADING_FALSE = "SET_CART_LOADING_FALSE";
export const FETCH_CART_LIST_SUCCESS = "FETCH_CART_LIST_SUCCESS";
export const FETCH_CART_LIST_FAIL = "FETCH_CART_LIST_FAIL";
