export const SET_LOADING_TRUE = "SET_Disease_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_Disease_LOADING_FALSE";

export const GET_DISEASE_LIST = "GET_DISEASE_LIST";

export const GET_ONE_DISEASE = "GET_ONE_DISEASE";
export const GET_ONE_DISEASE_ERROR = "GET_ONE_DISEASE_ERROR";
