export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";

export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";

export const SET_ONE_PRODUCT = "SET_ONE_PRODUCT";
