export const SET_LOADING_FALSE = "SET_LOADING_FALSE";
export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const CHANGE_TYPE_PRODUCT = "CHANGE_TYPE_PRODUCT";
export const CHANGE_TYPE_DISEASE = "CHANGE_TYPE_DISEASE";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const SET_QUERY_SEARCH = "SET_QUERY_SEARCH";
